# Generated by Django 6.0.2 on 2026-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(blank=True, choices=[('genius', 'Genius Olympiad'), ('robotex', 'Robotex'), ('ifest', 'iFest'), ('vex', 'VEX'), ('castic', 'CASTIC'), ('jwp', 'Junior Water Prize'), ('ioai', 'IOAI')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('atastian', models.BooleanField(default=False)),
                ('club', models.CharField(blank=True, choices=[('sousse', 'Sousse'), ('monastir', 'Monastir'), ('moknine', 'Moknine'), ('ksarhlel', 'Ksar Hellel')])),
                ('city', models.CharField(max_length=40)),
                ('team', models.BooleanField(default=False)),
                ('teammates', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('energy', 'Energy'), ('env', 'Environment'), ('art', 'Arts & Humanities'), ('software', 'Softwares & AI'), ('physics', 'Physics'), ('chemistry', 'Chemistry')], max_length=50)),
                ('project_title', models.CharField(blank=True, max_length=50)),
                ('project_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_members_number', models.PositiveIntegerField()),
                ('competition', models.CharField(choices=[('line_follower', 'Line Follower'), ('robofoot', 'RoboFoot'), ('smart_city', 'Smart City'), ('maze', 'Maze'), ('sumo', 'Sumo'), ('roborace', 'RoboRace'), ('firefighting', 'Firefighting'), ('coding_mission', 'Coding Mission')], max_length=30)),
                ('category', models.CharField(choices=[('poussins', 'Poussins'), ('juniors', 'Juniors'), ('colleges', 'Colleges'), ('seniors', 'Seniors')], max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
