# Generated by Django 6.0.2 on 2026-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
