# Generated by Django 6.0.2 on 2026-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oro', '0002_teams_rank_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OROSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_grader_released', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='teams',
            name='competition',
            field=models.CharField(choices=[('bowling', 'Bowling'), ('line_follower', 'Line Follower'), ('robofoot', 'RoboFoot'), ('smart_city', 'Smart City'), ('maze', 'Maze'), ('sumo', 'Sumo'), ('roborace', 'RoboRace'), ('firefighting', 'Firefighting'), ('coding_mission', 'Coding Mission')], max_length=30),
        ),
    ]
