# Generated by Django 6.0.2 on 2026-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. International · Competition', max_length=100),
        ),
    ]
