# Generated by Django 6.0.2 on 2026-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0003_latestnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='latest_news/'),
        ),
    ]
