# Generated by Django 6.0.2 on 2026-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0004_latestnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
