# Generated by Django 6.0.2 on 2026-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0005_alter_latestnews_id_alter_newsarticle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ifestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='ifest_video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
