# Generated by Django 6.0.2 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0007_ifestimage_delete_ifestvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('atastian', models.BooleanField(default=False)),
                ('club', models.CharField(choices=[('sousse', 'Sousse'), ('monastir', 'Monastir'), ('moknine', 'Moknine'), ('ksarhlel', 'Ksar Hellel')])),
                ('city', models.CharField(max_length=40)),
                ('team', models.BooleanField(default=False)),
                ('teammates', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('engineering', 'Engineering'), ('energy', 'Energy'), ('env', 'Environment'), ('art', 'Arts & Humanities'), ('software', 'Softwares & AI'), ('physics', 'Physics'), ('chemistry', 'Chemistry')], max_length=50)),
                ('project_title', models.CharField(max_length=50)),
                ('project_desc', models.TextField()),
            ],
        ),
    ]
