# Generated by Django 6.0.2 on 2026-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0008_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='competition',
            field=models.CharField(blank=True, choices=[('genius', 'Genius Olympiad'), ('robotex', 'Robotex'), ('ifest', 'iFest'), ('vex', 'VEX'), ('castic', 'CASTIC'), ('jwp', 'Junior Water Prize'), ('ioai', 'IOAI')], max_length=50),
        ),
    ]
