# Generated by Django 6.0.2 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0009_registration_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='categorie',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('energy', 'Energy'), ('env', 'Environment'), ('art', 'Arts & Humanities'), ('software', 'Softwares & AI'), ('physics', 'Physics'), ('chemistry', 'Chemistry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='club',
            field=models.CharField(blank=True, choices=[('sousse', 'Sousse'), ('monastir', 'Monastir'), ('moknine', 'Moknine'), ('ksarhlel', 'Ksar Hellel')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='project_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='project_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
