# Generated by Django 6.0.2 on 2026-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0010_alter_registration_categorie_alter_registration_club_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='latestnews',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. International · Competition', max_length=100),
        ),
    ]
