# Generated by Django 6.0.2 on 2026-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atast_web', '0011_delete_newsarticle_delete_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='description',
            field=models.TextField(),
        ),
    ]
